import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";
import Link from "next/link";
import BottomNavBar from "@/components/BottomNavBar";
import Divider from "@/components/Divider";
import { PageData } from "@/lib/consts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex flex-col h-screen text-white justify-center items-center w-full" style={{
          backgroundImage: "url('/our-projects-1.webp')",
          backgroundSize: "cover",
          backgroundPosition: "center",
        }}>
          <Navbar />
          <div className="flex flex-col justify-between items-center h-1/4 w-1/2 text-center flex-wrap">
            <h1 className="text-2xl lg:text-4xl">{PageData.header.title}</h1>
            <p className="text-lg lg:text-xl">
              {PageData.header.description}
            </p>
            <div className="flex space-x-5">
              <Link
                href="/about-us"
                className="text-black bg-white px-3 py-2.5 rounded-lg"
              >
                Learn More
              </Link>
              <Link
                href="/our-projects"
                className="text-white bg-transparent border px-3 py-2.5 rounded-lg"
              >
                Our Projects
              </Link>
            </div>
          </div>
        </header>
        <main className="p-4">{children}</main>
        <footer className="text-black">
          <Divider color="#000" />
          <BottomNavBar />
        </footer>
      </body>
    </html>
  );
}
